name: Listen issues
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: echo "${{ github.event }}"