name: Listen issues
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: Issue details
        run: echo "Title - ${{ github.event.issue.title }}, Body - ${{ github.event.issue.body }}, Action - ${{ github.event.action }}"